spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rideshare
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8080
  servlet:
    context-path: /api

jwt:
  secret: your-secret-key-here-should-be-very-long-and-secure
  expiration: 86400000 # 24 hours

app:
  cors:
    allowed-origins: http://localhost:5173